### ISSUE TITLE
Alpine DNS issues

### ISSUE THREAD

**Issue by chrislovecnm** [k8s-for-greeks/gpmr#14]
grrr... we may want to dump Alpine

> Alpine Linux does not support the search keyword in resolv.conf. This breaks many tools that rely on DNS service discovery (e.g. Kubernetes, Tutum.co, Consul).

https://github.com/janeczku/docker-alpine-kubernetes

@mward29 thoughts?

**Comment by chrislovecnm** [comment]
BTW `FROM alpine:edge` may fix this ... 3.4 is more sane

**Comment by chrislovecnm** [comment]
Edge is still not happy ... will let you resolve

**Comment by chrislovecnm** [comment]
Actually edge is fine.  The problem is that each pet is not registering there dns.  We need to determine how to setup dns.

**Comment by mward29** [comment]
What is the DNS for each pet used for?

**Comment by chrislovecnm** [comment]
Python needs to lookup C* seeds.  The petset developer needs to tell me what the records are.  `alpine:edge` dns works btw.
